services:
  drone-vc-p:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $BOT_TOKEN 
      DATABASE_URL: $DATABASE_URL
      BOT_OWNER: $BOT_OWNER
    resources:
      cpu: 1000m
      memory: 3Gi
